### ISSUE TITLE
Sugerencia :+1:

### ISSUE THREAD

**Issue by rosepac** [tipoqueno/vuejs-recursos-es#2]
@tipoqueno si lo deseas integrar por aquí [-recursos javascript-](https://github.com/DpdC/biblioteca-espanol-gratis#recursos-de-frameworks--de-javascript-construction-construction-construction-construction-construction), y si poco a poco, lo pudiésemos adaptar a [contribución](https://github.com/DpdC/biblioteca-espanol-gratis/blob/master/contribucion.md#acuerdo-de-licencia-del-contribuyente) entonces ya estaría de :100: , poco a poco, yo tengo mucho que acoplar.. aún.. :sob:

**Comment by tipoqueno** [comment]
¿Cuál es tu idea? Porque esta lista tiene un fin diferente: recursos sobre Vuejs (gratis y pagos) exclusivamente en español. Si te querés agregar cada recurso gratuito sos libre de hacerlo :)
